// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUhW_1GizLa8xHQxLb1uoSySpEfIXhpMg',
    appId: '1:307570190949:web:719e03cd41d6fdc61d348c',
    messagingSenderId: '307570190949',
    projectId: 'galaxy-fighter-2ede8',
    authDomain: 'galaxy-fighter-2ede8.firebaseapp.com',
    storageBucket: 'galaxy-fighter-2ede8.firebasestorage.app',
    measurementId: 'G-24PVZVD5ER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL-J-5FOlO1tGbJmDKh4hE91Bw3cLeZG0',
    appId: '1:307570190949:android:40e1ff2754398fcb1d348c',
    messagingSenderId: '307570190949',
    projectId: 'galaxy-fighter-2ede8',
    storageBucket: 'galaxy-fighter-2ede8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1D69QURkzkW12rUqZz4L73rZ40G6_fr8',
    appId: '1:307570190949:ios:23de257f527d532b1d348c',
    messagingSenderId: '307570190949',
    projectId: 'galaxy-fighter-2ede8',
    storageBucket: 'galaxy-fighter-2ede8.firebasestorage.app',
    iosBundleId: 'com.example.tapDodge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1D69QURkzkW12rUqZz4L73rZ40G6_fr8',
    appId: '1:307570190949:ios:23de257f527d532b1d348c',
    messagingSenderId: '307570190949',
    projectId: 'galaxy-fighter-2ede8',
    storageBucket: 'galaxy-fighter-2ede8.firebasestorage.app',
    iosBundleId: 'com.example.tapDodge',
  );
}
